[package]
name = "hirnfurz"
version = "0.1.0"
authors = ["Michael Craggs <m.e.craggs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1"
